pipeline {
  agent any

  tools {
    maven 'maven-3.6.3'
  }

  stages {
    stage('Build') {
      steps {
        sh 'mvn package -Dmaven.test.skip=true -U'
      }
    }

    stage('Make Container') {
      steps {
      sh "cp target/*.jar docker/"
      sh "docker build -t demo ./docker/"
      }
    }

  }
}