node {

    stages {
        stage('Prepare') {
             steps {
                 sh './jenkins/scripts/prepare.sh'
             }
        }
        stage('Build') {
            steps {
                sh './jenkins/scripts/build.sh'
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}